steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './sonarqube/Dockerfile' ,'--tag=asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:${_SONARQUBE_SCANNER_CLI_VERSION}', '--tag=asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:latest', './sonarqube']
  # args: 
  # - 'build'
  # - '--build-arg'
  # - 'SONARQUBE_SCANNER_CLI_VERSION=4.6.0.2311'
  # - '-t'
  # - 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:latest'
  # - '-t'
  # - 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:4.6.0.2311'
  # - '.'

images: 
- 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:latest'
- 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:${_SONARQUBE_SCANNER_CLI_VERSION}'


tags: ['sonardemo']
substitutions:
  _SONARQUBE_SCANNER_CLI_VERSION: 4.7.0.2747
