steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/helm:${_HELM_VERSION}', '--tag=asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/helm:latest', '--build-arg', 'HELM_VERSION=v${_HELM_VERSION}', '.']
# Sanity Check: make sure basic functionality works
- name: 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/helm:latest'
  args: ['version', '--client']
  env:
    - SKIP_CLUSTER_CONFIG=true
images:
  - 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/helm:${_HELM_VERSION}'
  - 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/helm:latest'
tags: ['helm-demo']
substitutions:
  _HELM_VERSION: 3.14.3