steps:
  - name: 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=maswanidev@gmail.com'
    - '-Dsonar.projectKey=jmc-devscops'
    - '-Dsonar.organization=jmc-devscops'
    - '-Dsonar.sources=.'
tags: ['sonartestdemo']
