steps:
  - name: 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login={specify}'
    - '-Dsonar.projectKey={specify}'
    - '-Dsonar.organization={specify}'
    - '-Dsonar.sources=.'
tags: ['testdemo']
